### ISSUE TITLE
Implement photoneutron physics

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1941]
OpenMC currently handles photoatomic interactions and atomic relaxation but isn't capable of handling photonuclear reactions.

To be clear, there are no current plans to implement this that I am aware of but I just wanted to create a placeholder issue in case anyone is ever planning to work on this.

**Comment by GuySten** [comment]
Basic photonuclear physics checklist:
* [ ] Extending Kalbach-Mann systematics to support incident photons #3682.
* [ ] Extending Inelastic Scattering to support incident photons #3675.
* [ ] Using NJOY2016 to create ACE-formatted photonuclear data libraries #3683.
* [ ] Defining hdf5 format photonuclear data for openmc and implementing openmc.data.IncidentPhotonuclear object to process it.
* [ ] Sample photonuclear reactions in openmc with support for biasing.
* [ ] Add photonuclear data to the official data libraries.
