### ISSUE TITLE
Tracking Issue for OpenDeplete Components

### ISSUE THREAD

**Issue by cjosey** [openmc-dev/openmc#977]
Now that OpenDeplete is part of OpenMC, I thought I'd just make a tracking issue for things that were left unfixed in the original OpenDeplete.  I also added things mentioned in the PR for this.  If it's preferred to break this up into separate issues, that's fine.  I just didn't want to email spam everyone with each issue.

- [x]  [Better handling of capture branching ratios](https://github.com/mit-crpg/opendeplete/issues/33) - We probably want to have the ability to do it right eventually, but group collapsed data is good enough for rudimentary work.  I wouldn't design a new reactor with it though.

- [x] [Better handling of energy deposition](https://github.com/mit-crpg/opendeplete/issues/34) - This just comes down to the choice between prompt or temporally accurate energy deposition.  Photon/charged particle transport is a whole separate issue.  On the upside, if we have temporally accurate deposition, then decay heat comes free.  The downside is trusting the data.

- [x] [Units in power](https://github.com/mit-crpg/opendeplete/issues/40) - I would extend this to perhaps including a unit consistency check.  Use whatever you'd like, and the code will tell you if it's dimensionally consistent.

- [x] Theory / methodology - Honestly, I could probably write this relatively quick by cleaning up chunks of my dissertation.

- [x] Decay only timesteps. - Relatively trivial so long as we ignore delayed neutrons.  If power = zero, then reaction rates = zero. Skip transport, we're done.

- [x] "Cleanly" handle fission yield energy dependence - It's not entirely clear we have sufficient quality data to do this right now.  I'd suggest adding an option that toggles from thermal, intermediate, and fast at _most_.

- [x] Smarter handling of decay chains - You can do a whole PhD on this (and I know people who are right now), but the easiest way is to create a directed graph and short-circuit nodes with half-lives below a specific value, assuming the reaction rates are zero.

- [x] V&V - Sounds "fun."

- [x] Public release of the high order integrators - I have the code.  Just need to tune it to the new codebase.

**Comment by SterlingButters** [comment]
I was actually just about to ask if OpenDepelete would be merged with OpenMC. When will the docs be updated for usage of this?

**Comment by paulromano** [comment]
I'd like to have at least a few of the issues identified here resolved (especially those relating to accuracy) before advertising the capability too much. The docs will definitely be updated by the next release though.

**Comment by SterlingButters** [comment]
Sweet, I’m excited
